
# 基本设置
title: PDQ881 加密视角
SEOTitle: PDQ881 加密视角 | OKX 交易与钱包 · Pi 币 & USDT 汇率博客
description: "面向加密投资者的独立博客，聚焦 OKX/欧易交易、okx.com 登录与下载、Web3 钱包使用、USDT 汇率与兑换（含 USDT→AED、人民币买 USDT）、Pi 币价值与 PI/USDT 兑换，以及 Ponke、Trump Coin、Joshua Block、Memefi 等热门话题。提供市场观察、教程与工具导航。"
keyword: "okx trading, 欧易官网地址, okx.com login, okx marketplace, okx app download, pi coin worth, okex crypto, usdt to aed, 欧易钱包, ponke chapter 2, okx download, 人民幣買usdt, memefi to usdt, pi 币, pi/usdt exchange, pi value, trump coin price, joshua block coin, 加密货币博客, Web3, Crypto Blog"
url: "https://pdq881.github.io"
baseurl: ""
github_username:    pdq881
header-img: img/post-bg-desk.jpg

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# 插件
plugins:
  - jekyll-paginate

# 排除文件
exclude:
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - less
